### ISSUE TITLE
Mac OS X: Up/Down arrow key for input history

### ISSUE THREAD

**Issue by nutinshell** [overtake/telegram#108]
It's very useful and handy :D

**Comment by jayallen** [comment]
+1

**Comment by JokerQyou** [comment]
+1

**Comment by cosmoretro** [comment]
+1

**Comment by overtake** [comment]
@cosmoretro i fixed this in beta. Wait next update or download beta:https://rink.hockeyapp.net/apps/c55f5e74ae5d0ad254df29f71a1b5f0e

**Comment by nutinshell** [comment]
@overtake in Version 1.71.23495 still can't use this feature?

**Comment by rsimsek-tgm** [comment]
@overtake in Version 1.81.29234 still can't use this feature.

**Comment by mrgluek** [comment]
Up/Down in version 2.00 switching between chats.
Cound you also add switching between chats with unread messages (like Alt+Shift+Up/Down in Slack)?
